title: Estude Agora
description: Vamos aprender juntos

url: http://erisvaldocarvalho.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Início
    url: /index.html
  - title: Sobre
    url: /about
  - title: Contato
    url: /contact

social:
  github: erisvaldocarvalho
  twitter: carvalhoforte
  facebook: carvalhoforte
  email: contato@erisvaldocarvalho.com.br
  instagram: carvalhoforte
  youtube: erisvaldocarvalho
  
google_analytics: "UA-58263416-1"
